version: "3.9"
services:
  rl_dev:
    container_name: rl_develop
    build: .
    image: macmacal/rl_devel:latest
    network_mode: host
    shm_size: 11gb
    volumes:
      - /mnt/storage/PAPER_1/from_battlestation/ws_phd:/mnt/ws
      - /mnt/storage/PAPER_1/from_battlestation/ws_phd/zshrc_docker:/home/user/.zshrc
      - /mnt/storage/PAPER_1/from_battlestation/ws_phd/zsh_history_docker:/home/user/.zsh_history
      - /mnt/storage/PAPER_1/from_battlestation/ws_phd/ray_results_eval:/home/user/ray_results
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: zsh
    env_file: env
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
